# Generated by Django 4.0.3 on 2022-03-26 00:56

from django.db import migrations, models
import meal_planner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', meal_planner.models.LowerCaseCharField(max_length=150, unique=True)),
                ('uom', models.CharField(max_length=10)),
                ('type', models.CharField(default='standard', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
