# Generated by Django 4.0.3 on 2022-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='on_hand',
            field=models.PositiveSmallIntegerField(default=33),
            preserve_default=False,
        ),
    ]
