# Generated by Django 4.0.1 on 2022-01-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='po',
            name='meal',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='PO',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
