# Generated by Django 4.0.3 on 2022-03-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('planned', models.SmallIntegerField(blank=True, null=True)),
                ('actual', models.SmallIntegerField(blank=True, null=True)),
                ('fruit_serving', models.FloatField(blank=True, default=0, null=True)),
                ('vegetable_serving', models.FloatField(blank=True, default=0, null=True)),
                ('fruit', models.ForeignKey(blank=True, limit_choices_to={'type': 'fruit'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_fruit', to='ingredients.ingredient')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='orders.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='recipes.recipe')),
                ('vegetable', models.ForeignKey(blank=True, limit_choices_to={'type': 'vegetable'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_vegatable', to='ingredients.ingredient')),
            ],
            options={
                'ordering': ['date', '-actual'],
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField()),
                ('put_out', models.PositiveSmallIntegerField()),
                ('left_over', models.PositiveSmallIntegerField()),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
        ),
    ]
