# Generated by Django 4.0.1 on 2022-01-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='MealIngredient',
        ),
    ]
