# Generated by Django 4.0.4 on 2022-05-12 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_fruit_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='actual',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Must be zero or larger')]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='planned',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Must be zero or larger')]),
        ),
    ]
