# Generated by Django 4.0.1 on 2022-02-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_ingredient_uom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
