# Generated by Django 4.0.1 on 2022-02-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_mealingredient_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.recipe'),
        ),
    ]
