# Generated by Django 4.0.1 on 2022-02-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_mealingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(related_name='ingredients', through='meals.MealIngredient', to='meals.Recipe'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='meals.recipe'),
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.recipe'),
        ),
        migrations.AlterField(
            model_name='po',
            name='meal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='po', to='meals.meal'),
        ),
    ]
