# Generated by Django 4.0.3 on 2022-03-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_meal_actual_alter_meal_planned'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealIngredient',
            new_name='RecipeIngredient',
        ),
    ]
