# Generated by Django 4.0.3 on 2022-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_rename_mealingredient_recipeingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='meals.RecipeIngredient', to='meals.ingredient'),
        ),
    ]
