# Generated by Django 4.0.3 on 2022-03-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='meals.po'),
        ),
        migrations.AddField(
            model_name='po',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
