# Generated by Django 4.0.3 on 2022-03-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_remove_po_meal_meal_po_po_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='serving',
            field=models.FloatField(),
        ),
    ]
