# Generated by Django 4.0.3 on 2022-03-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_recipeingredient_serving'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PO',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='po',
            new_name='Order',
        ),
    ]
