# Generated by Django 4.0.3 on 2022-03-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_rename_po_order_rename_po_meal_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['date', '-actual']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date', '-is_complete']},
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='Order',
            new_name='order',
        ),
    ]
