# Generated by Django 4.0.3 on 2022-03-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_alter_meal_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id', '-is_complete']},
        ),
    ]
