# Generated by Django 4.0.3 on 2022-03-20 04:32

from django.db import migrations
import meals.models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_alter_ingredient_options_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=meals.models.LowerCaseCharField(max_length=150, unique=True),
        ),
    ]
