# Generated by Django 4.0.3 on 2022-03-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='fruit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_fruit', to='meals.ingredient'),
        ),
        migrations.AddField(
            model_name='meal',
            name='fruit_serving',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='vegetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_vegatable', to='meals.ingredient'),
        ),
        migrations.AddField(
            model_name='meal',
            name='vegetable_serving',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
