from django.urls import path
from . import views


urlpatterns = [
    path("", views.meal_list, name="meals"),
    path("<int:pk>/edit/", views.MealEditView.as_view(), name="edit_meal"),
    path("<int:pk>/delete/",
         views.MealDeleteView.as_view(),
         name="delete_meal"),
    path("<int:pk>/add_fruits_and_veggies/",
         views.add_fruits_and_veggies,
         name="add_fruits_and_veggies"),
    path("<int:meal_pk>/fruit/create/",
         views.FruitCreateView.as_view(),
         name="create_fruit"),
    path("<int:meal_pk>/vegetable/create/",
         views.VeggieCreateView.as_view(),
         name="create_vegetable"),
    path("recipes/", views.recipe_list, name="recipes"),
    path("schedule/", views.meal_create_view, name="schedule_meal"),
    path("recipes/create/", views.recipe_create_view, name="create_recipe"),
    path("recipes/<int:pk>/update/",
         views.RecipeEditView.as_view(),
         name="update_recipe"),
    path("recipes/<int:pk>/delete/",
         views.RecipeDeleteView.as_view(),
         name="delete_recipe"),
    path("recipes/<int:recipe_pk>/ingredients/add",
         views.add_ingredient,
         name="add_ingredient"),
    path("recipes/<int:recipe_pk>/ingredients/<int:pk>/edit/",
         views.RecipeIngredientEditView.as_view(),
         name="edit_recipe_ingredient"),
    path("recipes/<int:recipe_pk>/ingredients/<int:pk>/delete/",
         views.recipe_ingredient_delete_view,
         name="delete_recipe_ingredient"),
    path("recipes/<int:recipe_pk>/ingredients/create/",
         views.IngredientCreateView.as_view(),
         name="create_ingredient"),
    path("print/", views.print_meals, name="print_meal"),
    path("orders/",
         views.OrderListView.as_view(),
         name="orders"),
    path("orders/create",
         views.OrderCreateView.as_view(),
         name="create_order"),
    path("orders/<int:pk>/update",
         views.OrderUpdateView.as_view(),
         name="update_order"),
    path("orders/<int:pk>/add_meals",
         views.add_meals_to_order,
         name="add_meals_to_order"),
    path("orders/<int:pk>/remove/<int:meal_pk>/",
         views.remove_meal_from_order,
         name="remove_meal_from_order"),
    path("orders/print/",
         views.print_orders,
         name="print_orders"),
]
