# Generated by Django 4.0.4 on 2022-05-12 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='serving',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Must be zero or larger')]),
        ),
    ]
