# Generated by Django 4.0.3 on 2022-03-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id', '-is_complete'],
            },
        ),
    ]
